trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: 'windows-latest'

#Maps the env variables
env:
  VERSION_SEMANITCS_CLIENT: '$(VersionSemanticsClient)'
  VERSION_SEMANITCS_CLIENT_ABSTRACTIONS: '$(VersionSemanticsClientAbstractions)'
  VERSION_SEMANITCS_MIGRATIONS: '$(VersionSemanticsMigration)'
  RELEASE_SEMANTICS: '$(ReleaseSemantics)'


variables:
  buildPlatform: 'Any CPU'
  BuildPlatformDirName: 'AnyCpu'
  buildConfiguration: 'Release'
  rootDir: '$(Build.SourcesDirectory)'
  oDataClientFactorySln: '$(rootDir)\sln\ODataClientFactory.sln'
  oDataMigrationSln: '$(rootDir)\sln\ODataMigration.sln'
  signigConfigPath: '$(rootDir)\configs'
  signingConfigFiles: '*.*'
  productBinPath: '$(rootDir)\bin\$(BuildPlatformDirName)\$(buildConfiguration)\Product'
  productFiles: 'Microsoft.OData.Extensions.*?(*.dll|*.config|*.pdb)'
  snExe: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\sn.exe'
  snExe64: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe'

stages: 
- stage: Build

  jobs:
    - job: Build
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet >=5.2.0'
        inputs:
          versionSpec: '>=5.2.0'


      - task: NuGetCommand@2
        displayName: 'NuGet restore'

      - task: VSBuild@1
        displayName: 'Build solution sln/ODataClientFactory.sln'
        inputs:
          solution: $(oDataClientFactorySln)
          vsVersion: "16.0"
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'

      - task: VSBuild@1
        displayName: 'Build solution sln/ODataMigration.sln'
        inputs:
          solution: $(oDataMigrationSln)
          vsVersion: "16.0"
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Running All Tests'
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Client Libraries'
        inputs:
          command: build
          arguments: --configuration=$(buildConfiguration)
          projects: |
                  $(rootDir)\src\Microsoft.OData.Extensions.Client\Microsoft.OData.Extensions.Client.csproj
                  $(rootDir)\src\Microsoft.OData.Extensions.Client.Abstractions\Microsoft.OData.Extensions.Client.Abstractions.csproj
          platform: '$(buildPlatform)'

      
      - task: DotNetCoreCLI@2
        inputs:
          command: custom
          custom: pack
          arguments: >
            $(rootDir)\src\Microsoft.OData.Extensions.Client.Abstractions\Microsoft.OData.Extensions.Client.Abstractions.csproj
            /p:NuspecFile=$(rootDir)\src\Microsoft.OData.Extensions.Client.Abstractions\Microsoft.OData.Extensions.Client.Abstractions.$(RELEASE_SEMANTICS).nuspec 
            --configuration=$(buildConfiguration) 
            --output=$(Build.ArtifactStagingDirectory)\Packages   
        displayName: Packing Client Abstractions

      - task: DotNetCoreCLI@2
        inputs:
          command: custom
          custom: pack
          arguments: >
            $(rootDir)\src/Microsoft.OData.Extensions.Client\Microsoft.OData.Extensions.Client.csproj
            /p:NuspecFile=$(rootDir)\src\Microsoft.OData.Extensions.Client\Microsoft.OData.Extensions.Client.$(RELEASE_SEMANTICS).nuspec 
            --configuration=$(buildConfiguration) 
            --output=$(Build.ArtifactStagingDirectory)\Packages 
        displayName: Packing Client 

      - task: DotNetCoreCLI@2
        inputs:
          command: custom
          custom: pack
          arguments: >
            $(rootDir)\src\Microsoft.OData.Extensions.Migration\Microsoft.OData.Extensions.Migration.csproj 
            /p:NuspecFile=$(rootDir)\src\Microsoft.OData.Extensions.Migration\Microsoft.OData.Extensions.Migration.$(RELEASE_SEMANTICS).nuspec 
            --configuration=$(buildConfiguration) 
            --output=$(Build.ArtifactStagingDirectory)\Packages 
        displayName: Packing  Migrations

      - publish: $(Build.ArtifactStagingDirectory)\Packages   
        displayName: Publish Build Artifacts  
        artifact: BuildPackages

      - publish: configs
        displayName: Publish Signing Scripts
        artifact: configs

        
- stage: CodeSign
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - deployment: CodeSign
    displayName: Code Signing
    pool:
      vmImage: windows-latest    
    environment: Code Sign - Approvals
    variables:
    - group: Code Signing
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: custom
              custom: tool
              arguments: install --tool-path . SignClient
            displayName: Install SignTool tool

          - pwsh: |
              .\SignClient "Sign" `
              --baseDirectory "$(Pipeline.Workspace)\BuildPackages" `
              --input "**/*.nupkg" `
              --config "$(Pipeline.Workspace)\configs\SignClient.json" `
              --filelist "$(Pipeline.Workspace)\configs\filelist.txt" `
              --user "$(SignClientUser)" `
              --secret "$(SignClientSecret)" `
              --name "Code Sign packages" `
              --description "Signing packages" `
              --descriptionUrl "https://github.com/OData/Extensions"
            displayName: Sign packages
              
          - publish: $(Pipeline.Workspace)/BuildPackages
            displayName: Publish Signed Packages
            artifact: SignedPackages